In [58]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
# Map 'Yes' to 1 and 'No' to 0
attrition_df['Attrition'] = attrition_df['Attrition'].map({'Yes': 1, 'No': 0})


attrition_df.head()

Age  Attrition     BusinessTravel              Department  \
0   41          1      Travel_Rarely                   Sales   
1   49          0  Travel_Frequently  Research & Development   
2   37          1      Travel_Rarely  Research & Development   
3   33          0  Travel_Frequently  Research & Development   
4   27          0      Travel_Rarely  Research & Development   

   DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                 1          2  Life Sciences                        2   
1                 8          1  Life Sciences                        3   
2                 2          2          Other                        4   
3                 3          4  Life Sciences                        4   
4                 2          1        Medical                        1   

   HourlyRate  JobInvolvement  ...  PerformanceRating  \
0          94               3  ...                  3   
1          61               2  ...                  4   
2          92               2  ...                  3   
3          56               3  ...                  3   
4          40               3  ...                  3   

  RelationshipSatisfaction  StockOptionLevel TotalWorkingYears  \
0                        1                 0                 8   
1                        4                 1                10   
2                        2                 0                 7   
3                        3                 0                 8   
4                        4                 1                 6   

   TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                      0               1               6                   4   
1                      3               3              10                   7   
2                      3               3               0                   0   
3                      3               3               8                   7   
4                      3               3               2                   2   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     5  
1                        1                     7  
2                        0                     0  
3                        3                     0  
4                        2                     2  

[5 rows x 27 columns]

In [59]:
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [60]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [61]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    'Age', 'DistanceFromHome', 'Education', 'JobLevel',
    'YearsSinceLastPromotion', 'NumCompaniesWorked', 'PercentSalaryHike',
    'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany'
]
# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
print(X_df.dtypes)

Age                        int64
DistanceFromHome           int64
Education                  int64
JobLevel                   int64
YearsSinceLastPromotion    int64
NumCompaniesWorked         int64
PercentSalaryHike          int64
TotalWorkingYears          int64
TrainingTimesLastYear      int64
YearsAtCompany             int64
dtype: object


In [62]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
# Create a StandardScaler
scaler = StandardScaler()
# Fit the StandardScaler to the training data
X_train_scaled = scaler.fit_transform(X_train)

# Scale the testing data
X_test_scaled = scaler.transform(X_test)

In [63]:
from sklearn.preprocessing import OneHotEncoder

# Initialize the OneHotEncoder
department_encoder = OneHotEncoder(sparse_output=False)
# Fit the encoder to the department column in the training data
department_encoder.fit(y_train[['Department']])

# Apply the encoder to the training data
y_train_dept_encoded = department_encoder.transform(y_train[['Department']])

# Apply the encoder to the testing data
y_test_dept_encoded = department_encoder.transform(y_test[['Department']])

# Display the transformed training data
print("One-hot encoded training data for the 'department' column (first 5 rows):")
print(y_train_dept_encoded[:5])

# Display the transformed testing data
print("\nOne-hot encoded testing data for the 'department' column (first 5 rows):")
print(y_test_dept_encoded[:5])

# Display the encoder's categories for reference
print("\nCategories for the 'department' column:")
print(department_encoder.categories_)

One-hot encoded training data for the 'department' column (first 5 rows):
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]

One-hot encoded testing data for the 'department' column (first 5 rows):
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]

Categories for the 'department' column:
[array(['Human Resources', 'Research & Development', 'Sales'], dtype=object)]


In [64]:
from sklearn.preprocessing import OneHotEncoder

# Initialize the OneHotEncoder
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the attrition column in the training data
attrition_encoder.fit(y_train[['Attrition']])

# Apply the encoder to the training data
y_train_attrition_encoded = attrition_encoder.transform(y_train[['Attrition']])

# Apply the encoder to the testing data
y_test_attrition_encoded = attrition_encoder.transform(y_test[['Attrition']])

# Display the transformed training data
print("One-hot encoded training data for the 'attrition' column (first 5 rows):")
print(y_train_attrition_encoded[:5])

# Display the transformed testing data
print("\nOne-hot encoded testing data for the 'attrition' column (first 5 rows):")
print(y_test_attrition_encoded[:5])

# Display the encoder's categories for reference
print("\nCategories for the 'attrition' column:")
print(attrition_encoder.categories_)


One-hot encoded training data for the 'attrition' column (first 5 rows):
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]

One-hot encoded testing data for the 'attrition' column (first 5 rows):
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]

Categories for the 'attrition' column:
[array([0, 1])]


In [65]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

# Find the number of columns in the X training data
input_features = X_train_scaled.shape[1]
print(f"Number of columns (features) in X training data: {input_features}")

# Create the input layer
input_layer = Input(shape=(input_features,), name="input_layer")

# Create at least two shared layers
shared_layer1 = Dense(64, activation='relu', name="shared_layer1")(input_layer)
shared_layer2 = Dense(32, activation='relu', name="shared_layer2")(shared_layer1)

# Output shared layers for later branching
print("Shared layers created successfully!")


Number of columns (features) in X training data: 10
Shared layers created successfully!


In [66]:
# Create a branch for Department
# Hidden layer for the department branch
department_hidden = Dense(16, activation='relu', name="department_hidden_layer")(shared_layer2)

# Output layer for the department branch
# Use softmax activation for multi-class classification
department_output = Dense(y_train_dept_encoded.shape[1], activation='softmax', name="department_output")(department_hidden)

print("Department branch created successfully!")


Department branch created successfully!


In [67]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer
# Create a branch for Attrition
# Hidden layer for the attrition branch
attrition_hidden = Dense(16, activation='relu', name="attrition_hidden_layer")(shared_layer2)

# Output layer for the attrition branch
# Use sigmoid activation for binary classification
attrition_output = Dense(1, activation='sigmoid', name="attrition_output")(attrition_hidden)

print("Attrition branch created successfully!")


Attrition branch created successfully!


In [68]:
from tensorflow.keras.models import Model

# Create the model
# Combine the input layer, shared layers, and the two branches
model = Model(
    inputs=input_layer,
    outputs=[department_output, attrition_output],
    name="Branching_Neural_Network"
)

# Compile the model
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',  # For multi-class classification
        'attrition_output': 'binary_crossentropy'        # For binary classification
    },
    metrics={
        'department_output': 'accuracy',
        'attrition_output': 'accuracy'
    }
)

# Summarize the model
model.summary()


Model: "Branching_Neural_Network"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer1 (Dense)     │ (None, 64)             │            704 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer2 (Dense)     │ (None, 32)             │          2,080 │ shared_layer1[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_hidden_layer   │ (None, 16)             │            528 │ shared_layer2[0][0]    │
│ (Dense)                   │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden_layer    │ (None, 16)             │            528 │ shared_layer2[0][0]    │
│ (Dense)                   │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             51 │ department_hidden_lay… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 1)              │             17 │ attrition_hidden_laye… │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 3,908 (15.27 KB)

 Trainable params: 3,908 (15.27 KB)

 Non-trainable params: 0 (0.00 B)

In [96]:
# Import dependencies
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
import tensorflow as tf

# Load the dataset
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')

# Inspect the dataset
print("Dataset columns:", attrition_df.columns)
print("First few rows of the dataset:")
print(attrition_df.head())

# Ensure no leading/trailing spaces in column names
attrition_df.columns = attrition_df.columns.str.strip()

# Map 'Yes' to 1 and 'No' to 0 for Attrition column
attrition_df['Attrition'] = attrition_df['Attrition'].map({'Yes': 1, 'No': 0})

# Verify the mapping
print("Unique values in 'Attrition' column after mapping:", attrition_df['Attrition'].unique())

# Define the target and feature columns
selected_columns = [
    'Age', 'DistanceFromHome', 'Education', 'JobLevel',
    'YearsSinceLastPromotion', 'NumCompaniesWorked', 'PercentSalaryHike',
    'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany'
]

y_df = attrition_df[['Attrition', 'Department']]  # Targets
X_df = attrition_df[selected_columns]            # Features

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

# One-hot encode the Department column
department_encoder = OneHotEncoder(sparse_output=False)
y_train_dept_encoded = department_encoder.fit_transform(y_train[['Department']])
y_test_dept_encoded = department_encoder.transform(y_test[['Department']])

# Extract and reshape the Attrition column for binary classification
y_train_attrition_encoded = y_train['Attrition'].values.reshape(-1, 1)
y_test_attrition_encoded = y_test['Attrition'].values.reshape(-1, 1)

# Scale the feature data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define the neural network model
input_layer = Input(shape=(X_train_scaled.shape[1],), name="input_layer")

# Shared layers
shared_layer1 = Dense(64, activation='relu', name="shared_layer1")(input_layer)
shared_layer2 = Dense(32, activation='relu', name="shared_layer2")(shared_layer1)

# Department branch
department_hidden = Dense(16, activation='relu', name="department_hidden_layer")(shared_layer2)
department_output = Dense(y_train_dept_encoded.shape[1], activation='softmax', name="department_output")(department_hidden)

# Attrition branch
attrition_hidden = Dense(16, activation='relu', name="attrition_hidden_layer")(shared_layer2)
attrition_output = Dense(1, activation='sigmoid', name="attrition_output")(attrition_hidden)

# Create the full model with both outputs
full_model = Model(inputs=input_layer, outputs=[department_output, attrition_output])

# Summarize the model
full_model.summary()

# Debug: Validate target shapes and contents
print("Model output names:", full_model.output_names)
print("Target for department_output (first 5):", y_train_dept_encoded[:5])
print("Target for attrition_output (first 5):", y_train_attrition_encoded[:5])

# Debug: Validate predictions
sample_output = full_model.predict(X_train_scaled)
print("Shape of department_output predictions:", sample_output[0].shape)
print("Shape of attrition_output predictions:", sample_output[1].shape)

# Debug: Validate target and output shapes
assert y_train_dept_encoded.shape[1] == full_model.get_layer('department_output').output.shape[-1], \
    "Mismatch between department_output shape and its target shape!"
assert y_train_attrition_encoded.shape[1] == full_model.get_layer('attrition_output').output.shape[-1], \
    "Mismatch between attrition_output shape and its target shape!"

# Train both outputs together
print("Training both outputs together...")
full_model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',  # Multi-class classification
        'attrition_output': 'binary_crossentropy'        # Binary classification
    },
    metrics={
        'department_output': 'accuracy',
        'attrition_output': 'accuracy'
    }
)

# Debug: Ensure loss dictionary keys match model outputs
print("Loss dictionary keys:", {
    'department_output': 'categorical_crossentropy',
    'attrition_output': 'binary_crossentropy'
}.keys())

# Debug: Validate training inputs
print(f"X_train_scaled shape: {X_train_scaled.shape}")
print(f"y_train_dept_encoded shape: {y_train_dept_encoded.shape}")
print(f"y_train_attrition_encoded shape: {y_train_attrition_encoded.shape}")

# Train the model
history = full_model.fit(
    X_train_scaled,
    {
        'department_output': y_train_dept_encoded,  # Correct target for department_output
        'attrition_output': y_train_attrition_encoded  # Correct target for attrition_output
    },
    epochs=10,
    batch_size=32,
    validation_data=(
        X_test_scaled,
        {
            'department_output': y_test_dept_encoded,  # Correct target for department_output
            'attrition_output': y_test_attrition_encoded  # Correct target for attrition_output
        }
    )
)
print("Model training completed!")

# Evaluate the model
eval_results = full_model.evaluate(
    X_test_scaled,
    {
        'department_output': y_test_dept_encoded,
        'attrition_output': y_test_attrition_encoded
    }
)

print("\nEvaluation Results:")
print(f"Department Output - Accuracy: {eval_results[3]:.2f}")
print(f"Attrition Output - Accuracy: {eval_results[4]:.2f}")



Dataset columns: Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')
First few rows of the dataset:
   Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & 

Model: "functional_42"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer1 (Dense)     │ (None, 64)             │            704 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer2 (Dense)     │ (None, 32)             │          2,080 │ shared_layer1[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_hidden_layer   │ (None, 16)             │            528 │ shared_layer2[0][0]    │
│ (Dense)                   │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden_layer    │ (None, 16)             │            528 │ shared_layer2[0][0]    │
│ (Dense)                   │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             51 │ department_hidden_lay… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 1)              │             17 │ attrition_hidden_laye… │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 3,908 (15.27 KB)

 Trainable params: 3,908 (15.27 KB)

 Non-trainable params: 0 (0.00 B)

Model output names: ListWrapper(['department_output', 'attrition_output'])
Target for department_output (first 5): [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
Target for attrition_output (first 5): [[0]
 [0]
 [0]
 [0]
 [0]]
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Shape of department_output predictions: (1176, 3)
Shape of attrition_output predictions: (1176, 1)
Training both outputs together...
Loss dictionary keys: dict_keys(['department_output', 'attrition_output'])
X_train_scaled shape: (1176, 10)
y_train_dept_encoded shape: (1176, 3)
y_train_attrition_encoded shape: (1176, 1)
Epoch 1/10


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 3)

In [97]:
# Evaluate the model with the testing data
# Evaluate the model
eval_results = full_model.evaluate(
    X_test_scaled,
    {
        'department_output': y_test_dept_encoded,
        'attrition_output': y_test_attrition_encoded
    },
    batch_size=32
)

# Display evaluation results
print("\nEvaluation Results:")
print(f"Department Output - Loss: {eval_results[1]:.4f}, Accuracy: {eval_results[3]:.4f}")
print(f"Attrition Output - Loss: {eval_results[2]:.4f}, Accuracy: {eval_results[4]:.4f}")


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 3)

In [98]:
# Print the accuracy for both department and attrition
# Evaluate the model
eval_results = full_model.evaluate(
    X_test_scaled,
    {
        'department_output': y_test_dept_encoded,
        'attrition_output': y_test_attrition_encoded
    },
    batch_size=32
)

# Display accuracy for both outputs
print("\nAccuracy Results:")
print(f"Department Output Accuracy: {eval_results[3]:.4f}")  # Accuracy for department_output
print(f"Attrition Output Accuracy: {eval_results[4]:.4f}")   # Accuracy for attrition_output


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 3)

1. Is accuracy the best metric to use on this data? Why or why not?
Accuracy can provide a quick understanding of the model's performance, but it may not always be the best metric for this dataset:

For department_output (multi-class classification), accuracy is reasonable because the classes are balanced, but metrics like precision, recall, and F1-score could give deeper insights into specific class performance.
For attrition_output (binary classification), accuracy may not be the best metric if the classes are imbalanced (e.g., many more "No" than "Yes"). Metrics like precision, recall, or AUC-ROC would be more informative in such cases, as they handle imbalanced data better.

2. What activation functions did you choose for your output layers, and why?
Department Output:
Activation: softmax
Reason: Softmax is ideal for multi-class classification problems. It produces probabilities for each class, ensuring they sum to 1, which makes it suitable for categorical cross-entropy loss.
Attrition Output:
Activation: sigmoid
Reason: Sigmoid is used for binary classification problems. It outputs probabilities between 0 and 1, which is compatible with binary cross-entropy loss.


3. Can you name a few ways that this model might be improved?
Feature Engineering:

Include interaction terms or derived features (e.g., ratios like YearsSinceLastPromotion / TotalWorkingYears).
Use domain knowledge to engineer more meaningful features.
Hyperparameter Tuning:

Experiment with learning rates, number of layers, units per layer, and activation functions.
Use grid search or random search to optimize hyperparameters.
Regularization:

Add dropout layers or L2 regularization to prevent overfitting.
Advanced Architectures:

Explore models like ensemble methods or decision-tree-based models (e.g., XGBoost) for comparison.
Use transfer learning if applicable to certain features.
Balanced Dataset:

Address potential class imbalances in the attrition data using oversampling, undersampling, or SMOTE (Synthetic Minority Oversampling Technique).
Evaluation Metrics:

Use metrics like AUC-ROC, precision, recall, and F1-score for a more comprehensive understanding of model performance.